Repository GFGRBU/Git-For-Geeks-3.0, pull requests merged in 2024-10, with the labels that each got.

#34 Saptanshu
  Saptanshu/ok.py
Labels: hacktoberfest-accepted

#39 Shushobhita
  CONTRIBUTING.md
  LICENSE
  README.md
  output/reverse.exe
Labels: hacktoberfest-accepted

#40 task done - Harshit&krish
  krish_singh/reverse.c
  krish_singh/reverse.exe
Labels: hacktoberfest, hacktoberfest-accepted

#37 Aaditya Hajari
  Aaditya-Hajari/reversenumbers.c
Labels: hacktoberfest-accepted

#42 Tejas somani
  TejasSomani/Reverse.java
Labels: hacktoberfest-accepted

#8 rev
  om/rev.c
Labels: hacktoberfest-accepted

#44 aryanJ
  main.c
Labels: hacktoberfest-accepted

#10 added .c
  khushi/reverse.c
Labels: hacktoberfest-accepted

#45 vaishnavi
  vaishnavi/reverse.py
Labels: hacktoberfest-accepted

#9 I want to contribute
  mrudul/reversenumber.py
Labels: hacktoberfest-accepted

#7 added reverse.c
  shubham/reverse.c
Labels: hacktoberfest-accepted, git-for-geeks-3.0

#6 pranay reverse number print code
  pranay/reverse.py
Labels: hacktoberfest-accepted, git-for-geeks-3.0

#46 Nikhil pr
  Nikhil/Sample.java
Labels: hacktoberfest-accepted

#47 Add files via upload
  akshat/w.py
Labels: hacktoberfest-accepted

#48 Added:5 c++ programs
  pravin/checkprimeornot.cpp
  pravin/factorial.cpp
  pravin/largestofthree.cpp
  pravin/reverse.cpp
  pravin/sumofn.cpp
Labels: hacktoberfest-accepted, git-for-geeks-3.0
